<?php
// This script and data application were generated by AppGini 5.95
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/landcruisers.php");
	include_once("{$currDir}/landcruisers_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('landcruisers');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout(function() { window.location = "index.php?signOut=1"; }, 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = 'landcruisers';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`landcruisers`.`manufacturer`" => "manufacturer",
		"if(`landcruisers`.`date`,date_format(`landcruisers`.`date`,'%m/%d/%Y'),'')" => "date",
		"`landcruisers`.`landcruisers_id`" => "landcruisers_id",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => '`landcruisers`.`date`',
		3 => 3,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`landcruisers`.`manufacturer`" => "manufacturer",
		"if(`landcruisers`.`date`,date_format(`landcruisers`.`date`,'%m/%d/%Y'),'')" => "date",
		"`landcruisers`.`landcruisers_id`" => "landcruisers_id",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`landcruisers`.`manufacturer`" => "Manufacturer",
		"`landcruisers`.`date`" => "Date",
		"`landcruisers`.`landcruisers_id`" => "Landcruisers id",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`landcruisers`.`manufacturer`" => "manufacturer",
		"if(`landcruisers`.`date`,date_format(`landcruisers`.`date`,'%m/%d/%Y'),'')" => "date",
		"`landcruisers`.`landcruisers_id`" => "landcruisers_id",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`landcruisers` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'landcruisers_view.php';
	$x->RedirectAfterInsert = 'landcruisers_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Landcruisers';
	$x->TableIcon = 'table.gif';
	$x->PrimaryKey = '`landcruisers`.`landcruisers_id`';

	$x->ColWidth = [150, 150, 150, ];
	$x->ColCaption = ['Manufacturer', 'Date', 'Landcruisers id', ];
	$x->ColFieldName = ['manufacturer', 'date', 'landcruisers_id', ];
	$x->ColNumber  = [1, 2, 3, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/landcruisers_templateTV.html';
	$x->SelectedTemplate = 'templates/landcruisers_templateTVS.html';
	$x->TemplateDV = 'templates/landcruisers_templateDV.html';
	$x->TemplateDVP = 'templates/landcruisers_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, ['user', 'group'])) { $DisplayRecords = 'all'; }
	if($perm['view'] == 1 || ($perm['view'] > 1 && $DisplayRecords == 'user' && !$_REQUEST['NoFilter_x'])) { // view owner only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `landcruisers`.`landcruisers_id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='landcruisers' AND LCASE(`membership_userrecords`.`memberID`)='" . getLoggedMemberID() . "'";
	} elseif($perm['view'] == 2 || ($perm['view'] > 2 && $DisplayRecords == 'group' && !$_REQUEST['NoFilter_x'])) { // view group only
		$x->QueryFrom .= ', `membership_userrecords`';
		$x->QueryWhere = "WHERE `landcruisers`.`landcruisers_id`=`membership_userrecords`.`pkValue` AND `membership_userrecords`.`tableName`='landcruisers' AND `membership_userrecords`.`groupID`='" . getLoggedGroupID() . "'";
	} elseif($perm['view'] == 3) { // view all
		// no further action
	} elseif($perm['view'] == 0) { // view none
		$x->QueryFields = ['Not enough permissions' => 'NEP'];
		$x->QueryFrom = '`landcruisers`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: landcruisers_init
	$render = true;
	if(function_exists('landcruisers_init')) {
		$args = [];
		$render = landcruisers_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: landcruisers_header
	$headerCode = '';
	if(function_exists('landcruisers_header')) {
		$args = [];
		$headerCode = landcruisers_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: landcruisers_footer
	$footerCode = '';
	if(function_exists('landcruisers_footer')) {
		$args = [];
		$footerCode = landcruisers_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
